jdk 17 build support

diff --git a/.github/workflows/product-is-builder-jdk17.yml b/.github/workflows/product-is-builder-jdk17.yml
--- a/.github/workflows/product-is-builder-jdk17.yml
+++ b/.github/workflows/product-is-builder-jdk17.yml
@@ -1,7 +1,10 @@
 name: product-is-builder-jdk17
 
-on: [push]
-
+on:
+  workflow_dispatch:
+  schedule:
+    # First day of each month at 15:00 UTC (8.30 PM SL time)
+    - cron:  '0 15 1 * *'
 
 env:
   MAVEN_OPTS: -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3
@@ -34,3 +37,21 @@ jobs:
           ls
           cd product-is/modules/integration/
           mvn clean install --batch-mode | tee mvn-build.log
+          PR_BUILD_STATUS=$(cat mvn-build.log | grep "\[INFO\] BUILD" | grep -oE '[^ ]+$')
+          PR_TEST_RESULT=$(sed -n -e '/\[INFO\] Results:/,/\[INFO\] Tests run:/ p' mvn-build.log)
+          PR_BUILD_FINAL_RESULT=$(
+            echo "==========================================================="
+            echo "product-is BUILD $PR_BUILD_STATUS"
+            echo "=========================================================="
+            echo ""
+            echo "$PR_TEST_RESULT"
+          )
+          PR_BUILD_RESULT_LOG_TEMP=$(echo "$PR_BUILD_FINAL_RESULT" | sed 's/$/%0A/')
+          PR_BUILD_RESULT_LOG=$(echo $PR_BUILD_RESULT_LOG_TEMP)
+          echo "::warning::$PR_BUILD_RESULT_LOG"
+          PR_BUILD_SUCCESS_COUNT=$(grep -o -i "\[INFO\] BUILD SUCCESS" mvn-build.log | wc -l)
+          if [ "$PR_BUILD_SUCCESS_COUNT" != "3" ]; then
+            echo "PR BUILD not successfull. Aborting."
+            echo "::error::PR BUILD not successfull. Check artifacts for logs."
+            exit 1
+          fi
